In [1]:
# “Data analysis is the process of collecting data, then inspecting, transforming, cleaning, and modeling data
#with the goal of discovering useful information, informing conclusions, and helping in decision-making.”

In [2]:
# pandas
# “Pandas is a package in Python that is used for inspecting (exploring), transforming, and cleaning data for data manipulation and analysis.
#It is built on top of NumPy.”

In [3]:
# pandas have two data structure
# 1)series:-It is a one-dimensional labeled array capable of holding any data type.
# 2) DataFrame: It is a two-dimensional labeled array. It looks like a table that means rows and columns.

In [4]:
pip install pandas

Requirement already satisfied: pandas in c:\users\verma\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\verma\anaconda3\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\verma\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\verma\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\verma\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\verma\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [1]:
import pandas as pd

In [7]:
l=[10,20,30,40]
s=pd.Series(l)
print(s)
print(s[0])

0    10
1    20
2    30
3    40
dtype: int64
10

In [8]:
l=[10,20,30,40]
s=pd.Series(l,index=["a","s","e","d"],dtype="float",name="pyhton")
print(s)
print(s["a"])

a    10.0
s    20.0
e    30.0
d    40.0
Name: pyhton, dtype: float64
10.0

In [9]:
d={"A":[10,20,30],"B":[100,200,300]}
s=pd.Series(d)
print(s)

A       [10, 20, 30]
B    [100, 200, 300]
dtype: object

In [15]:
d={"A":[10,20,30,40],"B":[100,200,300,400]}
df=pd.DataFrame(d)
df["sum"]=df["A"]+df["B"]
print(df)

    A    B  sum
0  10  100  110
1  20  200  220
2  30  300  330
3  40  400  440

In [3]:
s=pd.Series(12,index=[1,2,3,4,5,6,7])
print(s)

1    12
2    12
3    12
4    12
5    12
6    12
7    12
dtype: int64

In [4]:
s1=pd.Series(12,index=[1,2,3,4,5,6,7])
s2=pd.Series(12,index=[1,2,3,4])
print(s1+s2)

1    24.0
2    24.0
3    24.0
4    24.0
5     NaN
6     NaN
7     NaN
dtype: float64

DataFrame

In [5]:
l=[10,20,30,40]
df=pd.DataFrame(l)
print(df)
print(type(df))

    0
0  10
1  20
2  30
3  40
<class 'pandas.core.frame.DataFrame'>

In [6]:
d={"A":[1,2,3,4,5],"B":[10,20,30,40,50],"C":[100,200,300,400,500]}
df=pd.DataFrame(d,columns=["A","C"],index=["a","s","d","e","f"])
print(df)
print(df["C"]["a"])

   A    C
a  1  100
s  2  200
d  3  300
e  4  400
f  5  500
100

In [7]:
l=[[10,20,30,40],[100,200,300,400]]
df=pd.DataFrame(l)
print(df)

     0    1    2    3
0   10   20   30   40
1  100  200  300  400

In [8]:
d={"A":pd.Series([10,20,30,40]),"B":pd.Series([100,200,300,400])}
df=pd.DataFrame(d)
print(df)

    A    B
0  10  100
1  20  200
2  30  300
3  40  400

In [9]:
df=pd.DataFrame({"A":[10,20,30,40],"B":[100,200,300,400]})
df

    A    B
0  10  100
1  20  200
2  30  300
3  40  400

In [10]:
df["C"]=df["A"]+df["B"]
df

    A    B    C
0  10  100  110
1  20  200  220
2  30  300  330
3  40  400  440

In [11]:
df["D"]=df["A"]<=30
df

    A    B    C      D
0  10  100  110   True
1  20  200  220   True
2  30  300  330   True
3  40  400  440  False

In [12]:
df["E"]=df["A"][:3:]
df

    A    B    C      D     E
0  10  100  110   True  10.0
1  20  200  220   True  20.0
2  30  300  330   True  30.0
3  40  400  440  False   NaN

In [13]:
df.insert(1,"python",df["A"])
df

    A  python    B    C      D     E
0  10      10  100  110   True  10.0
1  20      20  200  220   True  20.0
2  30      30  300  330   True  30.0
3  40      40  400  440  False   NaN

In [14]:
df.insert(2,"python_1",[1000,2000,3000,4000])
df

    A  python  python_1    B    C      D     E
0  10      10      1000  100  110   True  10.0
1  20      20      2000  200  220   True  20.0
2  30      30      3000  300  330   True  30.0
3  40      40      4000  400  440  False   NaN

In [2]:
# how to read csv
df_app=pd.read_csv(r"C:\Users\verma\risk analytics\application_data (1).csv")
df_app

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,...,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
0,100002,1,Cash loans,M,N,Y,0,202500.0,406597.5,24700.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
1,100003,0,Cash loans,F,N,N,0,270000.0,1293502.5,35698.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
2,100004,0,Revolving loans,M,Y,Y,0,67500.0,135000.0,6750.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
3,100006,0,Cash loans,F,N,Y,0,135000.0,312682.5,29686.5,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
4,100007,0,Cash loans,M,N,Y,0,121500.0,513000.0,21865.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49994,157871,0,Cash loans,F,N,N,0,180000.0,1206000.0,45936.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
49995,157872,0,Cash loans,M,N,N,0,126000.0,1125000.0,47794.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
49996,157873,0,Cash loans,M,N,N,1,112500.0,900000.0,26316.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
49997,157874,0,Cash loans,F,N,Y,0,270000.0,820638.0,34897.5,...,0,0,0,0,0.0,0.0,0.0,0.0,2.0,4.0
49998,157875,0,Cash loans,F,N,Y,0,117000.0,254700.0,14751.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0

In [5]:
d={"A":[1,2,3,4,5],"B":[10,20,30,40,50],"C":[100,200,300,400,500]}
df=pd.DataFrame(d)
df.to_csv(r"C:\Users\verma\risk analytics\application_data (1).csv",index=False)